### ISSUE TITLE
TypeError: XLMRobertaModel.__init__() got an unexpected keyword argument 'safe_serialization'

### ISSUE THREAD

**Issue by seerahgpt** [seerahgpt/seerahgpt#1]
`$ python -m seerahgpt `
`
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/islam/.local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
[nltk_data]   Package punkt_tab is already up-to-date!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/islam/minhaz/seerahgpt/seerahgpt/__main__.py", line 46, in <module>
    pipeline = LocalRAGPipeline(host=args.host)
  File "/home/islam/minhaz/seerahgpt/seerahgpt/pipeline.py", line 45, in __init__
    Settings.embed_model = LocalEmbedding.set(host=host)
  File "/home/islam/minhaz/seerahgpt/seerahgpt/core/embedding/embedding.py", line 36, in set
    return HuggingFaceEmbedding(
  File "/home/islam/.local/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py", line 83, in __init__
    model = AutoModel.from_pretrained(
  File "/home/islam/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
  File "/home/islam/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4097, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: XLMRobertaModel.__init__() got an unexpected keyword argument 'safe_serialization'
`

**Comment by seerahgpt** [comment]
pip install --upgrade llama-index-embeddings-huggingface
